import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';

import 'package:raft_rumble/game/audio.dart';
import 'package:raft_rumble/game/battle.dart';
import 'package:raft_rumble/game/characters.dart';
import 'package:raft_rumble/game/save.dart';

/// The crew's voices, as shipped.
///
/// These clips are generated by `tool/gen_voice_sfx.dart` and committed as
/// assets, which means nothing at run time can tell you that a name the game
/// asks for has no file behind it, or that a clip came out silent, or that
/// one is four times louder than the rest. The failure is always the same
/// from the player's side — a character who makes no sound, or one who
/// shouts — and it is invisible in code review.
///
/// So the assets themselves are the thing under test.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  setUp(() => SaveService.instance.data = SaveData());

  File asset(String name) => File('assets/sfx/$name.wav');

  /// Peak, and mean-square over the part of the clip that is actually
  /// sounding.
  ///
  /// Gated rather than measured across the whole file, because clips have
  /// wildly different duty cycles — a laugh is "ha ha ha" and is nearly half
  /// silence, a hum is continuous — and averaging the silence in makes two
  /// equally loud clips look four times apart. What matters is how loud they
  /// are while you can hear them.
  ({double peak, double level, int samples}) measure(File f) {
    final bytes = f.readAsBytesSync();
    final view = ByteData.sublistView(Uint8List.fromList(bytes));
    var peak = 0.0;
    var sum = 0.0;
    var n = 0;
    var loud = 0;
    // 44-byte canonical header, which is what the generator writes.
    for (int i = 44; i + 1 < bytes.length; i += 2) {
      final v = view.getInt16(i, Endian.little) / 32768.0;
      if (v.abs() > peak) peak = v.abs();
      n++;
      if (v.abs() > 0.03) {
        sum += v * v;
        loud++;
      }
    }
    return (peak: peak, level: loud == 0 ? 0 : sum / loud, samples: n);
  }

  /// Every voice line the game is capable of asking for.
  Set<String> requestedVoices() {
    final names = <String>{};
    // Activities: drive every one through the real table.
    for (final act in CrewIdle.values) {
      if (act == CrewIdle.none) continue;
      final c = Crew(hp: 10, maxHp: 10);
      String? voice;
      for (int i = 0; i < 6000 && c.idle != act; i++) {
        c.idle = CrewIdle.none;
        c.idleT = 0;
        c.idleNextIn = 0;
        voice = c.updateIdle(0.016, allowNew: true) ?? c.startFireFlourish();
      }
      if (c.idle == act && voice != null) names.add(voice);
    }
    // Hit yelps.
    final c = Crew(hp: 10, maxHp: 10);
    for (int i = 0; i < 200; i++) {
      names.add(c.hitVoice());
    }
    // The fixed lines the world plays directly.
    names.addAll([
      'voice_grunt',
      'voice_laugh',
      'voice_cheer',
      'voice_gasp',
      'voice_brr',
      'voice_taunt',
      'voice_swap',
    ]);
    return names;
  }

  group('Every voice the game asks for exists', () {
    test('each requested clip has a file', () {
      for (final name in requestedVoices()) {
        expect(asset(name).existsSync(), true,
            reason: 'the game plays "$name" and there is no such asset');
      }
    });

    test('every character can speak every line in their own register', () {
      // A character with a register that has no variant of a clip falls
      // silently back to the mid one, which quietly undoes the whole point
      // of giving them different voices.
      for (final def in Cast.all) {
        final c = Crew(hp: 10, maxHp: 10, voice: def.voice);
        for (final base in AudioService.voiceBases) {
          final name = c.voiced(base);
          expect(asset(name).existsSync(), true,
              reason: '${def.id} speaks in ${def.voice.name} and there is no '
                  '"$name" for them to say');
        }
      }
    });

    test('every preloaded name resolves to a file', () {
      // The preloader walks its own list at startup; a name in it with no
      // file throws on the device and nowhere else.
      for (final base in AudioService.voiceBases) {
        for (final suffix in ['', '_low', '_high']) {
          expect(asset('$base$suffix').existsSync(), true,
              reason: '"$base$suffix" is preloaded but not shipped');
        }
      }
    });
  });

  group('The clips are actually usable', () {
    /// All shipped voice clips, variants included.
    List<File> allVoices() => Directory('assets/sfx')
        .listSync()
        .whereType<File>()
        .where((f) =>
            f.path.endsWith('.wav') &&
            f.path.split(RegExp(r'[\\/]')).last.startsWith('voice_'))
        .toList();

    test('none of them is silent', () {
      for (final f in allVoices()) {
        final m = measure(f);
        expect(m.samples, greaterThan(1000),
            reason: '${f.path} is barely any audio at all');
        expect(m.peak, greaterThan(0.2),
            reason: '${f.path} is inaudible (peak ${m.peak})');
      }
    });

    test('none of them clips', () {
      // A clip that runs into the rails buzzes, and it does it worst on a
      // phone speaker with several sounds layered over each other — which is
      // exactly when the crew are talking.
      for (final f in allVoices()) {
        expect(measure(f).peak, lessThan(0.96),
            reason: '${f.path} is clipping');
      }
    });

    test('they sit at comparable levels', () {
      // The failure this catches: one character's hum drowning out another
      // character's yelp. Before levelling, the set spanned a factor of
      // eighty in power — around nineteen decibels, which is the difference
      // between a mutter and a shout.
      //
      // Five is deliberately not tight. Seven decibels is ordinary variation
      // for a hand-authored voice set and some of it is wanted: a sneeze
      // should be louder than somebody counting their ammunition. This is
      // here to catch a clip that has come out broken, not to flatten every
      // line to the same volume.
      final loud = <String, double>{};
      for (final f in allVoices()) {
        loud[f.path] = measure(f).level;
      }
      expect(loud, isNotEmpty);
      final hottest = loud.values.reduce((a, b) => a > b ? a : b);
      final quietest = loud.values.reduce((a, b) => a < b ? a : b);
      expect(hottest / quietest, lessThan(5),
          reason: 'the loudest voice clip carries '
              '${(hottest / quietest).toStringAsFixed(1)}x the energy of the '
              'quietest');
    });
  });
}
